-- Keja: property listings
create type property_type as enum (
    'bedsitter', 'single', 'studio',
    'one_bed', 'two_bed', 'three_bed', 'four_plus_bed',
    'sq', 'maisonette', 'townhouse', 'standalone',
    'commercial'
);

create type furnishing as enum ('none', 'semi', 'full');
create type listing_status as enum ('draft', 'active', 'rented', 'inactive');

create table public.properties (
    id                  uuid primary key default gen_random_uuid(),
    owner_id            uuid not null references public.profiles(id) on delete cascade,
    -- Optional: when an agent lists on behalf of an owner, owner_id is the
    -- agent's profile and listed_by_agent=true. We do NOT model the absentee
    -- landlord separately at MVP — they aren't users of Keja.
    listed_by_agent     bool not null default false,

    title               text not null check (length(title) between 8 and 140),
    description         text not null check (length(description) between 30 and 4000),
    property_type       property_type not null,
    bedrooms            int not null check (bedrooms between 0 and 12),
    bathrooms           int not null check (bathrooms between 1 and 8),
    furnishing          furnishing not null default 'none',

    rent_kes            int not null check (rent_kes between 1000 and 10000000),
    deposit_months      int not null default 1 check (deposit_months between 0 and 6),
    viewing_fee_kes     int not null default 0 check (viewing_fee_kes between 0 and 5000),
    service_charge_kes  int not null default 0,

    county              text not null,                        -- 'Nairobi'
    sub_county          text,                                 -- 'Dagoretti North'
    estate              text not null,                        -- 'Kilimani'
    address_line        text,
    location            geography(Point, 4326),               -- (lng, lat)

    -- Amenities/facts as a structured JSON blob. Keys are stable; UI maps
    -- them to icons. See lib/property/amenities.ts for the full taxonomy.
    -- Examples: {water:"24h", electricity:"tokens", parking:true,
    --            wifi:false, gym:false, pets_allowed:false, balcony:true,
    --            backup_water:true, security:"24h_guard"}
    amenities           jsonb not null default '{}'::jsonb,

    rent_control_flagged bool not null default false,         -- legacy units < KES 2,500/mo

    status              listing_status not null default 'draft',
    listed_at           timestamptz,
    rented_at           timestamptz,
    expires_at          timestamptz,                          -- agents on subscription get longer TTLs

    -- search cache: regenerated by trigger
    search_tsv          tsvector,

    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now()
);

create index properties_status_idx          on public.properties(status) where status = 'active';
create index properties_estate_idx          on public.properties(estate);
create index properties_county_idx          on public.properties(county);
create index properties_type_idx            on public.properties(property_type);
create index properties_rent_idx            on public.properties(rent_kes);
create index properties_bedrooms_idx        on public.properties(bedrooms);
create index properties_owner_idx           on public.properties(owner_id);
create index properties_location_gix        on public.properties using gist (location);
create index properties_search_gix          on public.properties using gin (search_tsv);
create index properties_amenities_gin       on public.properties using gin (amenities);

create trigger properties_touch
    before update on public.properties
    for each row execute function public.touch_updated_at();

-- Search vector keeps title/estate/description/amenity-keys searchable in one shot.
create or replace function public.properties_refresh_search_tsv()
returns trigger language plpgsql as $$
begin
    new.search_tsv :=
        setweight(to_tsvector('simple', unaccent(coalesce(new.title, ''))),       'A') ||
        setweight(to_tsvector('simple', unaccent(coalesce(new.estate, ''))),      'A') ||
        setweight(to_tsvector('simple', unaccent(coalesce(new.sub_county, ''))),  'B') ||
        setweight(to_tsvector('simple', unaccent(coalesce(new.county, ''))),      'C') ||
        setweight(to_tsvector('simple', unaccent(coalesce(new.description, ''))), 'D');
    return new;
end;
$$;

create trigger properties_search_tsv_refresh
    before insert or update of title, estate, sub_county, county, description
    on public.properties
    for each row execute function public.properties_refresh_search_tsv();

-- Media: photos, videos, 360 tours. Storage bucket 'property-media' holds files.
create type media_kind as enum ('photo', 'video', 'tour_360');

create table public.property_media (
    id           uuid primary key default gen_random_uuid(),
    property_id  uuid not null references public.properties(id) on delete cascade,
    kind         media_kind not null default 'photo',
    storage_path text not null,                              -- supabase storage key
    width        int,
    height       int,
    duration_s   int,                                        -- video only
    sort_order   int not null default 0,
    created_at   timestamptz not null default now()
);

create index property_media_property_idx on public.property_media(property_id, sort_order);

-- Lightweight view-counter so we can show "viewed N times this week"
create table public.property_views (
    property_id  uuid not null references public.properties(id) on delete cascade,
    viewer_id    uuid references public.profiles(id) on delete set null,
    viewed_at    timestamptz not null default now()
);
create index property_views_property_time_idx on public.property_views(property_id, viewed_at desc);

-- Favourites
create table public.favourites (
    user_id      uuid not null references public.profiles(id) on delete cascade,
    property_id  uuid not null references public.properties(id) on delete cascade,
    created_at   timestamptz not null default now(),
    primary key (user_id, property_id)
);
